#CFLAGS+=-pthread
#CFLAGS+=-Wall
#LDFLAGS+=-pthread


Target: main.o single.o mkdir.o downWeb.o size-color.o picture.o top.o writeTheRest.o cp2win.o price.o search.o getTDK.o
	gcc main.o single.o mkdir.o downWeb.o size-color.o picture.o top.o writeTheRest.o cp2win.o price.o search.o getTDK.o -o haha -pthread -Wall

#Target: main.o single.o mkdir.o downWeb.o size-color.o picture.o top.o writeTheRest.o cp2win.o price.o search.o
#	gcc main.o single.o mkdir.o downWeb.o size-color.o picture.o top.o writeTheRest.o cp2win.o price.o search.o -o haha -pthread -Wall

clean:
	rm -f *.o haha
