Target: main.o downWeb.o size-color.o picture.o top.o writeTheRest.o cp2win.o price.o
	gcc main.o downWeb.o size-color.o picture.o top.o writeTheRest.o cp2win.o price.o -o haha -Wall


clean:
	git rm -f *.o haha
	rm -f *.o haha
